#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Usage: $(basename $0) NAME"
    exit 1
fi

NAME=$1

ip=$(uvt-kvm ip ${NAME})
release=$(ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" ubuntu@${ip} lsb_release -cs)

# Enable proposed in the guest
cat <<EOF >/tmp/ubuntu-${release}-proposed.list
# Enable Ubuntu proposed archive
deb http://archive.ubuntu.com/ubuntu/ ${release}-proposed restricted main multiverse universe
deb-src http://archive.ubuntu.com/ubuntu/ ${release}-proposed restricted main multiverse universe
EOF
scp -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" \
    /tmp/ubuntu-${release}-proposed.list ubuntu@$(uvt-kvm ip ${NAME}):
ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" ubuntu@${ip} \
    sudo mv ubuntu-${release}-proposed.list /etc/apt/sources.list.d

# Enable source packages and install all the typical dev tools
ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" ubuntu@$(uvt-kvm ip ${NAME}) << EOF
sudo sed -i "s/^# deb-src/deb-src/g" /etc/apt/sources.list
sudo add-apt-repository --yes ppa:canonical-kernel-team/proposed
sudo apt update --yes
sudo apt upgrade --yes
sudo apt dist-upgrade --yes
sudo apt install --yes dpkg-dev fakeroot gcc make quilt devscripts ubuntu-dev-tools
EOF

scp -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" $HOME/.bashrc ubuntu@$(uvt-kvm ip ${NAME}):
